### ISSUE TITLE
Gapless audio possible?

### ISSUE THREAD

**Issue by MartinGruenewald** [PCigales/DLNAmpvRenderer#1]
MPV would be able to play audio files without gaps in between. Would it be possible to have this via DNLA as well? So far, I've only foobar2000 playing gapless as a DNLA client.
REgards,
Martin

**Comment by PCigales** [comment]
I understand what you mean, the transition between two audio files is rather quick (it depends on the DLNA controller, I have tested with DLNAPlayOn, the delay is very short), but not instantaneous. The gapless playback is a feature which is very poorly documented and supported in the DLNA ecosystem, there is hardly anything about that in the official guidelines. The UPnP standards mention an optional SetNextAVTransportURI() action for providing seamless transition, and from what I understand, gapless playback relies on this command, but I cannot find anything about the way it should be implemented (a search on Google only gives one and a half page of useless results). I am going to make further researchs.

Meanwhile, you can use a workaround which is to send a playlist of the audio tracks to mpv rather than all the files. For example, with DLNAPlayOn, you can create a file called playlist.lst (an extension different from m3u or wpl must be used so that the script does not attempt to load the content of the playlist) containing the first line #EXTM3U and then lines with the pathes to the files (C:\DDD\XXX.mp3\r\nC:\DDD\YYY.mp3...); this playlist can be sent to DLNAmpvRenderer with the command playon c -p XXXX -n DLNAmpvRenderer -t n "playlist.lst" -o where XXXX is the port to be used. I have tested with an album whith tracks continuing one another and it gave the expected result.

**Comment by MartinGruenewald** [comment]
Thank you so much for the detailled explanation. Everytime, I test a new mediaplayer, the B-side of Abbey Road (by The Beatles) is my first test. You can't listen to it with pleasure, when it's not playing seamlessly.
And as mpv would play every format that I need (even bitstreamed Dolby Atmos), a gapless DNLA interface would be perfect. 
As far as I understood, OpenHome works with playlists for this purpose - generated by the control app. But the OpenHome-Server (BubbleUpnp in my case) doesn't send this whole list to the DNLA client, but track after track. 
But I'll have a look if your playlist suggestion could help me.

**Comment by PCigales** [comment]
You are welcome.
Oh, yes, the medley of the B-side of Abbey Road. I am certainly not as music lover as you are to be bothered by small gaps between tracks, but it is the very kind of album that deserves seamless playback.
So, I found some information about how gapless playback should be possible through DLNA, on particular in this thread: https://yabb.jriver.com/interact/index.php?topic=68934.0. I especially noticed: "No wonder noone implemented SetNextAVTransportURI  as it is totally underspecified and guess work. There is almost 0 chance a random
Control Point SetNextAVTransportURI   implementation work against a random Renderer SetNextAVTransportURI  implementation without testing it." and the fact that the two devs could not come to an agreement on how to implement the reporting of the track transition from the renderer to the controller, so in the jungle of DLNA, incompatibility is very likely between softwares and devices supposed to support the feature.
I also asked the dev of BubbleUPnP to explain how its app expects the renderer to behave, and he gave me some details.
I updated the script with an attempt to support gapless playback, which needs  the use of the "-g" option. It seems to work with BubbleUPnP (the feature must be enabled in the settings specific to the renderer in the app in the panel displaying the DLNA devices found). The dev told me that the app only triggers seamless playback for consecutive tracks of a same album. Maybe you could try the new script (from the main page, not from the releases) and let me know if it works as you expect (possibly testing different values for related settings of mpv such as "gapless-audio" and "prefetch-playlist").

There are indeed several ways to get gapless playback:
- using SetNextAVTransportURI provided both the controller and the renderer support this optional action, and subject to compatibility between the two parts (lottery...)
- sending a playlist with the tracks to the renderer if it can handle that
- live concatenating all the tracks into a unique stream in a lossless format (PCM, FLAC...) for example using ffmpeg and cast it to the renderer

For all these reasons, I would need to know more precisely what you are trying to get, in particular:
- where are the media contents (same PC, other device as a http server or a DLNA server) ?
- what controller app is used and on which device ?

**Comment by MartinGruenewald** [comment]
So great, that you're investigating in this topic. And very interesting, what you've found out.

I'll try this as soon as I am home this evening.
But to answer your questions: 
My music and my videos are stored on a Synology NAS, and a BubbleUPnP server is running there as well. For playing my media, I have an Intel NUC 8 with Windows 11 running. And my favourite way to control it would be Bubble DS or BubbleUpnp on my smartphone. 
My DNLA servers are Asset (for music) or Jellyfin. 
So far, JRiver (demo version) and foobar2000 were the only DNLA clients I found, where I could set the "gapless" checkbox in BubbleUPnP (and it worked with albums). 
(On a Raspberry Pi it worked with gmrender-resurrect as well - but the Pi Kernel is very limited with playing surround via HDMI.)
So - I'll write again as soon as I've checked you new -g option!

**Comment by MartinGruenewald** [comment]
It works with BubbleUpnp!
"prefetch-playlist" seems to be necessary, but now I have the option to set your renderer to "gapless" on my BubbleUpnp server. Then I can use it as an OpenHome device, and it plays in fact gapless. When I use the BubbleUpnp App as my DNLA controller it does so as well (without the server). Great.
Thank you so much!

**Comment by PCigales** [comment]
I am glad it works. From the tests I made, "prefetch-playlist" does not seem to be necessary with local contents or contents from fast servers with low latency, but it has to be used otherwise. For example, it is not needed with contents provided by BubbleUPnP DLNA server when using BubbleUPnP controller, but it becomes needed if using a controller from another device.
As explained in the readme, the option can be added to mpv.bat or mpv.conf. I prefer not activate it by default as the manual of mpv indicates that it can induce wrong results when per-file options are used, which is the case of DLNAmpvRenderer.
If you are interested, I have also upgraded DLNAPlayOn, which is both a DLNA controller, a DLNA client and a proxy server, to support gapless playback; thanks to the buffering the script makes, "prefetch-playlist" does not appear to be requested, as the content can be immediately delivered to mpv when retrieved. Nevertheless, I have not tested it with the DLNA servers you mentioned.

**Comment by MartinGruenewald** [comment]
Yes, you are right - "prefetch-playlist" was only necessary, while I tested at work. At home in my local network, it plays fine without it. 
Now I have an additional question: I've ripped my SACD-collection to DSF-files, which are packed in WavPack-containers (which reduces the size a lot). It's no problem to play them with mpv, because ffmpeg can handle them. But via DNLA with your program, it doesn't work. 
I've tried to add 
'http-get:*:audio/x-wavpack:*,' \
'http-get:*:audio/wavpack:*,' \

but mpv tells me on a console:
[ffmeg/demuxer] wv: Cannot determine additional parameter

Do you have an idea why? With drag and drop the file decodes.

**Comment by PCigales** [comment]
Otherwise, when needed, you can now use "-g p" instead of "-g" to activate the "prefetch-playlist" option in mpv.

Regarding your question, the script does not deal whatsoever whith the content of the media, it only knows their uri and their metadata, and its relationship with the server where they are stored is limited to a "head" request to check the accessibility of the resource and get the headers of the response that will be sent to mpv.
The problem you face comes from the fact that, in the DLNA protocol, a controller is supposed to ask a renderer which formats it can support, through a "GetProtocolInfo" request, and the renderer sends a kind of manifest, called a "sink", where all these formats are listed. The DLNA guidelines define mandatory and optional formats, and this list is rather limitative. Breaking this rule, DLNA Controllers can either be relaxed and ignore (and even not request) these infos, or remain strict, and refuse to send a content with a format which is not in the liste, or do real time transcoding to the nearest format. BubbleUPnP let you choose: in the settings of each renderer, you can choose to check mime types or not.
The format you are trying to play through DLNA is not part of the usual ones, and even less of the ones listed in the guidelines. So you have several possibilities: remux to a DLNA supported format, configure BubbleUPnP (or other controller) so that it accepts to cast contents whose format is not declared as supported by the renderer, or add the mime type of the format to the list it reports to the controller. It is what I have done for you: if you look from line 1910 to 2337 of the script, you will find this "sink", and towards the end, new added mime types, among which "http-get:*:audio/x-wavpack:*,". I have tested with BubbleUPnP with mime type checking activated, and it worked. I used a sample from "https://filesamples.com/formats/wv".
I don't understand why your attempt, as you mention that you tried to add this mime-type ended with an error in mpv.
