### ISSUE TITLE
Cant find UPNP Renderer

### ISSUE THREAD

**Issue by lucfig** [PCigales/DLNAmpvRenderer#2]
Hi,

First of all, thanks for the script. I was looking for a way to run a UPNP renderer in Windows that only runs and fullscreen and found your script.

I followed all steps and managed to run MPV with the bat file. MPV was quickly minimized and I can see the name of the renderer and the port in the title bar.

However, even after allowing MPV and Python in Firewall exceptions for all ports, I cannot manage to see the UPNP renderer.

Is there a troubleshooting or any suggestion to solve this?

Thanks and regards.

**Comment by PCigales** [comment]
Hi,

you are welcome, I hope we will find a solution to this problem.

I would need a few more information as issues related to upnp renderer detection can have many causes. Could you, please, indicate what upnp controller you use and if it runs on the same or on another device, and also provide the command line from which the script was launched ? Could you also precise if you manage to have another dlna  renderer, such as the one embedded in Windows Media Player, visible to your dlna controller ?

If you are positive you granted the required authorizations in the firewall, you can try to add the "-b" argument in the command line, so that the script listens and advertises on all network interfaces.

You can also add "-v 2" to increase the level of verbosity, and watch in the log displayed if the search messages sent by the dlna controller are received or not.

Another idea is to try to first run the renderer, wait a few seconds, and after that launch the controller, and then stop both and do the opposite, as there are two mechanisms in the discovery protocol.

If the controller that you use runs on another device, you could also check if the renderer can be detected by a controller from the same host (in this repository, there is another script called dlnaplayon that can serve for that purpose, and it can operate on all network interfaces with the right arguments).

Good luck, sorry for my poor English, and I stay available to bring more assistance.
